# Numpy Bacsic

---



## Import Numpy

In [1]:
import numpy as np

## Creating Arrays

In [26]:
# Creat a 1-D array containing the values 1, 2, 3

arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [27]:
# Create 2-D array contaning two arrays with the values 1, 2, 3 and 4, 5, 6

arr2 = np.array([[1,2,3],[4,5,6]])

arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# Create a 3-D array with 2-D array, both contraining two arrays with the values 1, 2, 3 and 4, 5, 6

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [29]:
# Check how many dimensions arrays have:

print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [34]:
# Create an array with 5 dimensions and verify that is has 5 dimentsions:

arr_ndim = np.array([1,2,3,4], ndmin=5)

arr_ndim

array([[[[[1, 2, 3, 4]]]]])

## Numpy Array Indexing

In [36]:
# Get the first element from the following array

arr_idx = np.array([1,2,3,4,5])

arr_idx[0]

1

In [38]:
# Get third and fourth element from the following array and add them

arr_idx2 = np.array([1,2,3,4,5])

arr_idx2[2] + arr_idx2[3]
# 3 + 4 = 7

7

In [44]:
# Access the element on the first row, second columns and second row, second columns

arr_idx3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(f'2nd element on 1st row:' , arr_idx3[0,1])

print(f'2nd element on 2st row:' , arr_idx3[1,1])

2nd element on 1st row: 2
2nd element on 2st row: 7


In [49]:
# Access the third element of the second array of the first array

arr_idx4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(f'Print array 3-D: \n', arr_idx4)

arr_idx4[0,1,2]

Print array 3-D: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6

In [56]:
# Print the last element from the 2nd 2dnim:

arr_idx5 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('Last element the from 2nd ndim: ', arr_idx5[1,-1]) # 10
print(arr_idx5[1,-2]) # 9

Last element the from 2nd ndim:  10
9


## Numpy Array Slicing

We pass slice instead of index like this: `[start:end]`.

We can also define the step, like this: `[start:end:step]`.

In [59]:
# Slice elements from index 1 to index 5 from the following array:

arr_sc = np.array([1,2,3,4,5,6,7])

print('Print from index 1 to index 5: ', arr_sc[1:5])

# Slice elements from index 2 to index 6 from the following array:

print('Print from index 2 to index 6: ', arr_sc[2:6])


Print from index 1 to index 5:  [2 3 4 5]
Print from index 2 to index 6:  [3 4 5 6]


In [60]:
# Scice elements from the beginning to index 4 (not included):

arr_sc1  = np.array([1,2,3,4,5])

arr_sc1[:4]

array([1, 2, 3, 4])

In [61]:
# Scice elements from the index 3 the end to 1 index from the end

arr_sc2 = np.array([1,2,3,4,5])

arr_sc2[-3:-1]

array([3, 4])

In [64]:
# Return every other element from index 1 to index 5 [start:end:step]

arr_sc3 = np.array([1,2,3,4,5,6,7,8,9,10])

print('Print from index 1 to index 5: ' , arr_sc3[1:5:2])

# Return every other element from the entire array:

print('Print entire array: ' , arr_sc3[::2])

Print from index 1 to index 5:  [2 4]
Print entire array:  [1 3 5 7 9]


In [67]:
# From the second element, scile elements from index 1 to index 4 (not included):

arr_sc4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('Print from index 1 to index 4: ', arr_sc4[1,1:4])

Print from index 1 to index 4:  [7 8 9]


In [68]:
# From both elements, return 2 index

print('Print return 2 index: ', arr_sc4[0:2,2])

Print return 2 index:  [3 8]


In [70]:
# From the both elements, slice index 1 to index 4, this will return a 2D array:

print('Print return 2D array: \n', arr_sc4[0:2,1:4])

Print return 2D array: 
 [[2 3 4]
 [7 8 9]]


## Numpy Data Types

By default Python have these data types:

- `strings` - used to represent text data, the text is given under quote marks. e.g. "ABCD"

- `integer` - used to represent integer numbers. e.g. -1, -2, -3

- `float` - used to represent real numbers. e.g. 1.2, 42.42

- `boolean` - used to represent True or False.

- `complex` - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in Numpy:

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type ( void )

In [74]:
# Get the data type of an array containing strings:

arr_ty = np.array(['apple', 'banana', 'cherry'])

arr_ty.dtype

dtype('<U6')

In [76]:
# Create an array with data type string

arr_ty2 = np.array([1, 2, 3], dtype='S')

arr_ty2.dtype

dtype('S1')

In [77]:
# Create an array with data type 4 bytes integer

arr_ty3 = np.array([1, 2, 3], dtype='i4')

arr_ty3.dtype

dtype('int32')

In [79]:
# Chage data type from float to integer be using 'int' as parameter value:

arr_ty4 = np.array([1.1, 2.1, 3.1])

new_arr = arr_ty4.astype('int')

new_arr.dtype

dtype('int64')

In [81]:
# Chage data type integer to boolean be using 'bool' as parameter value:

arr_ty5 = np.array([1, 0, 3])

new_arr2 = arr_ty5.astype('bool')

new_arr2

array([ True, False,  True])

## Numpy Array copy vs view

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [82]:
# Make a copy, chage the original array, and display both arrays:

arr_copy = np.array([1, 2, 3, 4, 5])
x = arr_copy.copy()
x[0] = 42

print(arr_copy)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [83]:
# Make a view, chage the original array, and display both arrays:

arr_view = np.array([1, 2, 3, 4, 5])
y = arr_view.view()
y[0] = 42

print(arr_view)
print(y)

[42  2  3  4  5]
[42  2  3  4  5]


## Numpy Array shape

The shape of an array is the number of elements in each dimension.

In [84]:
# Print the shape of a 2D array:

arr_shape = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr_shape.shape

(2, 4)

## Numpy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [88]:
# Covert the follwing 1D array with 12 elements into a 2D array
# The outermost dimentsion will have 4 arrays, each with 3 elements

arr_res = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr_res = arr_res.reshape(4,3)

arr_res

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
# Convert the follwing 1D array with 12 elements into a 3D array
# The outmost dimension will have 4 arrays, each with 3 elements

arr_res1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr_res1 = arr_res1.reshape(2,3,2)

arr_res1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Returns Copy or View?

In [94]:
# Check if the returned array is a copy or a view

arr_res2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = arr_res2.reshape(2, 4).base

print(x)
print(arr_res2)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


### Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass `-1` as the value, and NumPy will calculate this number for you.

In [98]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr_res3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

new_arr3 = arr_res3.reshape(2, 2, -1)

print(new_arr3.shape)

print(new_arr3)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the Arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [99]:
# Convert the array into a 1D array
arr_res4 = np.array([[1, 2, 3], [4, 5, 6]])

new_arr4 = arr_res4.reshape(-1)

new_arr4

array([1, 2, 3, 4, 5, 6])

## Numpy Array Iterating

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [100]:
# Iterate on the elements of the following 1-D array:

array_iter = np.array([1, 2, 3])

for x in array_iter:
  print(x)

1
2
3


In [101]:
# Interate on te elements of the follwing 2-D array:

array_iter2 = np.array([[1, 2, 3], [4, 5, 6]])

for x in array_iter2:
  print(x)

[1 2 3]
[4 5 6]


In [102]:
# Interate on each scaler element of the 2D array:

array_iter3 = np.array([[1, 2, 3], [4, 5, 6]])

for rows in array_iter3:
  for cols in rows:
    print(cols)

1
2
3
4
5
6


In [103]:
# Interate on the elements of the follwing 3D array:

arr_iter4  = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr_iter4:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [104]:
# Interate on each scaler element of the 3D array:
arr_iter5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for rows in arr_iter5:
  for cols in rows:
    for elements in cols:
      print(elements)

1
2
3
4
5
6
7
8
9
10
11
12


### Interating Array Using nditer()

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.


In [105]:
# Iterate through the following 3D array

arr_iter6 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr_iter6):
  print(x)

1
2
3
4
5
6
7
8


### Iterating Array With Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`.

In [107]:
# Iterating through the array as a string

arr_iter7 = np.array([1, 2, 3])

for x in np.nditer(arr_iter7, flags=['buffered'], op_dtypes=['S']):
  print(x)

x.dtype

b'1'
b'2'
b'3'


dtype('S21')

### Iterating With Different Step Size
We can use filtering and followed by iteration.

In [110]:
# Iterate through every scaler element of the 2D array skipping 1 element

arr_iter8 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

for x in np.nditer(arr_iter8[:, ::2]):
  print(x)

1
3
5
7
9
11


### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the `ndenumerate()` method can be used for those usecases.

In [111]:
# Enumerate on following 1D arrays elements

arr_iter9 = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr_iter9):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [112]:
# Enumerate on following 2 arrays elements

arr_iter10 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr_iter10):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Numpy Joining Array

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [114]:
# Join two arrays

arr_join1 = np.array([1, 2, 3])

arr_join2 = np.array([4, 5, 6])

arr_join = np.concatenate((arr_join1, arr_join2))

arr_join

array([1, 2, 3, 4, 5, 6])

In [115]:
# Join two 2D arrays along rows (axis = 1)

arr_j1 = np.array([[1, 2], [3, 4]])

arr_j2 = np.array([[5, 6], [7, 8]])

arr_j3 = np.concatenate((arr_j1, arr_j2), axis=1)

arr_j3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the `stack()` method along with the axis. If axis is not explicitly passed it is taken as 0.

In [118]:
arr_stack1 = np.array([1, 2, 3])

arr_stack2 = np.array([4, 5, 6])

arr_stack3 = np.stack((arr_stack1, arr_stack2), axis=1)

arr_stack3

array([[1, 4],
       [2, 5],
       [3, 6]])

### Stacking Along Rows
NumPy provides a helper function: `hstack()` to stack along rows.

In [119]:
arr_hstack = np.hstack((arr_stack1, arr_stack2))

arr_hstack

array([1, 2, 3, 4, 5, 6])

### Stacking Along Columns
NumPy provides a helper function: `vstack()`  to stack along columns.

In [121]:
arr_vstack = np.vstack((arr_stack1, arr_stack2))

arr_vstack

array([[1, 2, 3],
       [4, 5, 6]])

### Stacking Along Height (depth)
NumPy provides a helper function: `dstack()` to stack along height, which is the same as depth.

In [124]:
arr_dstack = np.dstack((arr_stack1, arr_stack2))

arr_dstack

array([[[1, 4],
        [2, 5],
        [3, 6]]])

## Numpy Splitting Array

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits.

In [133]:
# split the array in 3 parts:

arr_split = np.array([1, 2, 3, 4, 5, 6])

new_arr_split = np.array_split(arr_split, 3)

print('Print 3 parts: ', new_arr_split)

# Split the array in 4 parts:

new_arr_split2 = np.array_split(arr_split, 4)

print('Print 4 parts: ', new_arr_split2)

Print 3 parts:  [array([1, 2]), array([3, 4]), array([5, 6])]
Print 4 parts:  [array([1, 2]), array([3, 4]), array([5]), array([6])]


### Split Into Arrays
The return value of the `array_split()` method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [134]:
# Accsess the splited arrays:

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.array_split(arr, 3)

print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[1 2]
[3 4]
[5 6]


### Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the `array_split()` method, pass in the array you want to split and the number of splits you want to do.

In [137]:
# Split the 2D array into three 2D arrays:

arr_split = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

new_arr_split = np.array_split(arr_split, 3)

print(new_arr_split)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [142]:
# Split the 2D array into three 2D arrays long rows

arr_split3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr_split2 = np.array_split(arr_split3, 3, axis=1)

print(new_arr_split2)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [143]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

new_arr_split3 = np.hsplit(arr_split3, 3)

print(new_arr_split3)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Numpy Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.


In [145]:
# To search an array, use the `where()` method
# Find the indexes where the value is 4:

arr_search = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr_search == 4)

print(x)

(array([3, 5, 6]),)


In [148]:
# Find the indexes where the values are even:

arr_search2 = np.array([1, 2, 3, 4, 5, 4, 4])

arr_even = np.where(arr_search2 % 2 == 0)

print(arr_even)

# Find the indexes where the values are odd:

arr_odd = np.where(arr_search2 % 2 == 1)

print(arr_odd)


(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


### Search Sorted

There is a method called `searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [149]:
# Find the indexes where the value 7 should be inserted:

arr_search3 = np.array([6, 7, 8, 9])

x = np.searchsorted(arr_search3, 7)

print(x)

1


### Search From the Right Side
By default the left most index is returned, but we can give `side='right'` to return the right most index instead.

In [151]:
# Find the indexes where the value 7 should be inserted, starting from the right:

arr_search4 = np.array([6, 7, 8, 9])

x = np.searchsorted(arr_search4, 7, side='right')

print(x)

2


### Multiple Values

To search for more than one value, use an array with the specified values.


In [155]:
# Find the indexes where the values 2, 4, and 6 should be inserted:

arr_search5 = np.array([1, 3, 5, 7])

x = np.searchsorted(arr_search5, [1, 3, 7])

print(x)

[0 1 3]


## NumPy Sorting Arrays

Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [156]:
# The NumPy ndarray object has a function called sort(), that will sort a specified array.
# sort the array

arr_sort = np.array([3, 2, 0, 1])

print(np.sort(arr_sort))

[0 1 2 3]


In [157]:
# Sort the array alphabetically

arr_sort2 = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr_sort2))

['apple' 'banana' 'cherry']


In [158]:
# sort the array boolean

arr_sort3 = np.array([True, False, True])

print(np.sort(arr_sort3))

[False  True  True]


In [163]:
# Sort a 2D array

arr_sort2d = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr_sort2d))

[[2 3 4]
 [0 1 5]]


## NumPy Filter Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

If the value at an index is `True` that element is contained in the filtered array, if the value at that index is `False` that element is excluded from the filtered array.

In [164]:
# Create an array from the elements on index 0 and 2:

arr_fiter = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr_fiter[x]

print(newarr)

[41 43]


In [166]:
#Create a filter array that will return only values higher than 42:

arr_filter2 = np.array([41, 42, 43, 44])

filter_arr = []

for x in arr_filter2:
  if x > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

print(filter_arr)

[False, False, True, True]


In [167]:
# Create a filter array that will return only even elements from the original array:

arr_filter3 = np.array([41, 42, 43, 44])

filter_arr_1 = []

for x in arr_filter3:
  if x % 2 == 0:
    filter_arr_1.append(True)
  else:
    filter_arr_1.append(False)

print(filter_arr_1)

[False, True, False, True]


In [168]:
#Create a filter array that will return only values higher than 42:

arr_filter4 = np.array([41, 42, 43, 44])

filter_arr_2 = arr_filter4[arr_filter4 > 42]

print(filter_arr_2)

[43 44]


In [170]:
# Create a filter array that will return only even elements from the original array:

arr_filter4 = np.array([41, 42, 43, 44])

filter_arr_3 = arr_filter4[arr_filter4 % 2 == 0]

print(filter_arr_3)

[42 44]
